### ISSUE TITLE
Use email to register players/adventures

### ISSUE THREAD

**Issue by megawario** [megawario/awesome-sauce#13]
A user should be able to supply the email when
- creating an adventure
- subscribing to an adventure

Required:
- Field for email input
- Database security constrains (so emails will not be shared)
- Backend to support the operation.

**Comment by megawario** [comment]
Authentication will be created by using passport for nodejs.

# This issue must be reevaluated.

Passport suport third party auth.
Post requests for adventure updates and player updates must be evaluated to add auth.

**Comment by tronjob** [comment]
Superceded by issue #31
