### ISSUE TITLE
UI elements in wrong language

### ISSUE THREAD

**Issue by tronjob** [megawario/awesome-sauce#14]
- When hovering the add adventure button, the onhover text is in English, when the rest of the page is in Portuguese.
- When editing adventure, the Cancel button is in English

**Comment by megawario** [comment]
Portuguese is the default language for the site.
Mayby in the future we should add components for multilanguage.

**Comment by tronjob** [comment]
Yeah, I presumed as much. As soon as I pull the project into my machine I'll fix the strings ;)
Multilanguage might be an interesting feature for players that only speak english

**Comment by megawario** [comment]
To go on next patch.
Fixed in #25.
