### ISSUE TITLE
Improve interface for mobiles

### ISSUE THREAD

**Issue by nuno-al** [megawario/awesome-sauce#15]
The plataform is not very mobile friendly.
- Buttons too small.
- The list is too wide for small screens.
- Text too small.
- The design is not responsive overall.

**Comment by megawario** [comment]
It will be taken into consideration of next release.
Low priority though and can be pushed back.

Possible solutions:
- on mobile, redirect to possible Android app.
- do some enchancing for mobile use.

**Comment by megawario** [comment]
Checking Jquery Mobile (https://jquerymobile.com/).
Will review the interface using jquery mobile instead of jquery UI and achieve a cleaner look.

**Comment by megawario** [comment]
Doing as part of angular change, using bootstrap.
