### ISSUE TITLE
GET requests to / not redirecting properly

### ISSUE THREAD

**Issue by tronjob** [megawario/awesome-sauce#26]
When a user makes a GET request to / (by entering thebard.pt:8080 instead of the direct url), an error is thrown: Error: Cannot GET /.

This is due to a suitable route for this path not being present and redirecting traffic properly. This is an easy fix that improves the usability of the site and allows for a shorter URL to be shared.

**Comment by megawario** [comment]
Should be fixable when using a webserver to serve the node pages.
This will be required also for port 80.
More information on the subject is needed.
