### ISSUE TITLE
Add direct links to adventures

### ISSUE THREAD

**Issue by tronjob** [megawario/awesome-sauce#27]
When sharing adventures, it would be useful to have a direct link to the specific adventure instead of just the non-specific website URL (i.e. thebard.pt/id/12345 instead of thebard.pt). 

This way a DM or a player would be able to show others their adventure/the adventure they're playing on, instead of just a possibly large list of adventures.

**Comment by megawario** [comment]
Not on this scope.

This would require a new type of site where a page site would be an adventure page.
This is an enhancement to be done on a possible new project that integrates with this api services.
