### ISSUE TITLE
Add a <title> to the main page

### ISSUE THREAD

**Issue by tronjob** [megawario/awesome-sauce#32]
Currently the main page has no `<title>`tag, so the page's tab title is the full URL, which looks quite ugly.
A title should be added for aesthetic and conformity

**Comment by megawario** [comment]
It is not a bug, it is a feature, without title, there is nothing to steal our user's attention!!!!

**Comment by tronjob** [comment]
Going in as part of the auth pull request

**Comment by megawario** [comment]
Auth pull request didnt fix. (probably missed on merge).
Changed it and it is on WIP.
